title: <p align="center"> Nivedita Abhijit Deshpande </p>

logo: <p align="center">"images/Capture.PNG?raw=true"</p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nivedita-deshpande/">LinkedIn</a> |
  <a href="https://github.com/nd2712">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Information Technology and Management at Naveen Jindal School of Management, The University of Texas at Dallas.
  <br><br>
  I am currently looking for Spring 2022 co-op opportunities while pursuing the Business Intelligence and Analytics track with a focus on Data Analytics and Data Science domain.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
